Frame1
Gijol/gijol-frontend pull request #4
Opened 2022-04-26 16:31 UTC by hyojaeKwon

프레임 1에 대한 전반적인 구성 완료

뒤 배경에는 사진 같은거 넣어도 될 것 같습니다.

2022-04-27 02:47 UTC, ChoiEungi requested changes
리뷰 드렸습니다! 디자인 시안대로 구현이 잘 됐네요 👍

2022-04-27 02:47 UTC, ChoiEungi commented on src/pages/frames/frame1/frame1.tsx
> +const Frame1 = function Frame1(): JSX.Element {
`mainFrame` 혹은 `FirstFrame`은 어떨까요?

2022-04-27 02:47 UTC, ChoiEungi commented on src/pages/frames/frame1/styles.ts
> +  /* justify-content: center; */
불필요한 주석은 지원도 좋을듯 합니다 :)

2022-04-27 02:47 UTC, ChoiEungi commented on src/pages/frames/frame1/styles.ts
> +  margin: 0;
global style로 설정하는건 어떨까요?

2022-04-27 17:48 UTC, hyojaeKwon commented on src/pages/frames/frame1/styles.ts
> +  margin: 0;
아직 디자인 시안이 정확히 완성이 안되어서 global style설정은 후위로 미뤘습니다.

2022-04-28 01:33 UTC, ChoiEungi approved these changes
잘 반영해주셨네요! 고생하셨어요~

2022-04-28 14:42 UTC, merged

2022-04-28 14:42 UTC, hyojaeKwon commented
close #5 #3